### ISSUE TITLE
Add file searching completion time logging

### ISSUE THREAD

**Issue by GeorgeShao** [GeorgeShao/PowerSearch#21]

**Comment by karx1** [comment]
Hey, I'd love to work on this, so if you could assign me, that would be great!

**Comment by GeorgeShao** [comment]
@karx1 Sounds great! I've just assigned it to you. Should be a fairly simple PR.

**Comment by GeorgeShao** [comment]
Hi @karx1 since you haven't started yet and I really want to move on quickly with this project and build out more features - I'll be completing this issue/PR. I've unassigned you.
